### ISSUE TITLE
Add Menu bar and icon

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/VideoWatcher#17]
I assume we will need a menu icon/button to be able to change settings, export things, etc.  Can we:
- Add a menu bar to the right of the screen when in landscape mode or at the bottom of the screen when in portrait mode.   I think it should fit in the black area to the right of the panels on landscape mode.  For portrait, we will have to "make room" by pushing the panel area up.
- Add just one icon to that bar for now: a "hamburger menu", which when selected brings up a full-screen dialog box simply reading "cancel" for now.

**Comment by tedbarnett** [comment]
![image](https://github.com/tedbarnett/VideoWatcher/assets/694013/51c6d22d-4b81-44dd-bef2-68e11c35b466)

![image](https://github.com/tedbarnett/VideoWatcher/assets/694013/5be8c4af-ba7a-4fe9-9209-f326fa49a37c)

**Comment by bhautikpatoliya004** [comment]
@tedbarnett As per the Apple guidelines, we must add a menu icon on the top navigation bar instead of the Right side and at the bottom.
So, I’ve added a round shape menu button on the top right corner of the screen in both landscape and portrait mode. And it looks good. Also, I’ve used Apple’s default Menu to show different options under it.

**Comment by tedbarnett** [comment]
Great idea!
