### ISSUE TITLE
Skip launch screen, intro screen instead if library is empty

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/VideoWatcher#26]
We don't need to show the "Barnett Labs" splash screen since things seem to load pretty quickly. Instead, only if the user has no videos selected yet, let's show a mostly-text splash screen with the following text:

Welcome to VideoWatcher. To start, add videos from your Apple Photo library, or from Google Drive or Dropbox. Click the "+" sign above to start that process.

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Currently, we have flow like, App launch > Splash screen > Checking is there any video available in local database?, If available, moved to video panel screen otherwise stay at "Import video from Photo Library" screen.

So from above description what I understood, 
1. Need to remove splash screen
2. Check is there any video available in local database? If available, moved to panel screen, otherwise show text in centre of screen (Welcome to VideoWatcher. To start, add videos from your Apple Photo library, or from Google Drive or Dropbox. Click the "+" sign above to start that process.) And remove "Import video from Photo Library" Button and add + button top right side.
3. Click on + button to open small menu with list items, Photo Library, Google Drive and Dropbox.

Now, my question is if user tap on any one option(Photo Library, Google Drive and Dropbox.) and selected videos then which screen I need to show next?

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Right now, I added "Play video ->" button when import process done to go to video panel screen.

**Comment by tedbarnett** [comment]
Good call. Works!
