### ISSUE TITLE
"Manage Clips"

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/VideoWatcher#28]
Need to clarify difference between videos and clips.  So...
- Let's rename "Manage Videos" to "Manage Clips"
- Remove the "+" from that window (we will add new videos elsewhere)
- change swiping action to: swipe to the left for delete, swipe to the right to rename. 
- Add text at bottom of screen reading "Swipe left to delete. Swipe right to rename. Open clip to share."
- if a clip is played, add a share button to that screen so the clip can be shared

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Currently, when click on clip in Manage video screen, I opened Apple's default player. So, we can't customise its UI. So if we want to add share button while clip played then I need to create video player manually. Otherwise, we can add share button to the right side of the clip list cell. Please see attached screenshot and let me know your thoughts.

![Simulator Screenshot - iPhone 14 Pro - 2023-08-22 at 18 48 00](https://github.com/tedbarnett/VideoWatcher/assets/114083934/b67a5764-2910-4b49-92d2-2525da7701fa)

**Comment by tedbarnett** [comment]
Great solution!
